import Mock from 'mockjs'
var {info} = Mock.mock({
    "info":[
        {
            k:'心墙',
            n:'0987'
        },
        {
            k:'林俊杰',
            n:'1235'
        },
        {
            k:'Keep me alive',
            n:'9876'
        },
        {
            k:'答案',
            n:'2313'
        },
        {
            k:'失语者',
            n:'0989'
        },
        {
            k:'薛之谦',
            n:'6754'
        },
        {
            k:'陈奕迅',
            n:'8767'
        },
        {
            k:'意外',
            n:'0098'
        },
        {
            k:'香水有毒',
            n:'4567'
        },
        {
            k:'邓紫棋',
            n:'7657'
        },
        {
            k:'梦里花',
            n:'1342'
        },
        {
            k:'孤勇者',
            n:'7756'
        }
    ]
})

Mock.mock('/api/hotSearch','get',()=>{
    return{
        message:'获取成功',
        data:info,
        status:200
    }
})